{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2020-10755",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "all openstack-cinder versions before openstack-cinder 14.1.0"
                                },
                                {
                                    "version_value": "all openstack-cinder 15.x.x versions before openstack-cinder 15.2.0"
                                },
                                {
                                    "version_value": "all openstack-cinder 16.x.x versions before openstack-cinder 16.1.0"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "Red Hat"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "An insecure-credentials flaw was found in all openstack-cinder versions before openstack-cinder 14.1.0, all openstack-cinder 15.x.x versions before openstack-cinder 15.2.0 and all openstack-cinder 16.x.x versions before openstack-cinder 16.1.0. When using openstack-cinder with the Dell EMC ScaleIO or VxFlex OS backend storage driver, credentials for the entire backend are exposed in the ``connection_info`` element in all Block Storage v3 Attachments API calls containing that element. This flaw enables an end-user to create a volume, make an API call to show the attachment detail information, and retrieve a username and password that may be used to connect to another user's volume. Additionally, these credentials are valid for the ScaleIO or VxFlex OS Management API, should an attacker discover the Management API endpoint. Source: OpenStack project"
            }
        ],
        "metrics": [
            {
                "cvss-v_3_0": {
                    "vectorString": "6.5/CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N",
                    "version": "3.0"
                }
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "CWE-ID": "CWE-522",
                        "description": "CWE-522",
                        "lang": "eng",
                        "type": "CWE"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://wiki.openstack.org/wiki/OSSN/OSSN-0086",
                "refsource": "MISC",
                "url": "https://wiki.openstack.org/wiki/OSSN/OSSN-0086"
            },
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-10755",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-10755"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}