{
    "CVE_data_meta": {
        "ASSIGNER": "security-advisories@github.com",
        "ID": "CVE-2019-16784",
        "STATE": "PUBLIC",
        "TITLE": "Local Privilege Escalation present only on the Windows version of PyInstaller",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "< 3.6"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "PyInstaller"
                }
            ]
        },
        "credits": [
            {
                "lang": "eng",
                "value": "This vulnerability was discovered and reported by Farid AYOUJIL (@faridtsl), David HA, Florent LE NIGER and Yann GASCUEL (@lnv42) from Alter Solutions (@AlterSolutions) and fixed in collaboration with Hartmut Goebel (@htgoebel)."
            }
        ],
        "descriptions": [
            {
                "lang": "eng",
                "value": "In PyInstaller before version 3.6, only on Windows, a local privilege escalation vulnerability is present in this particular case: If a software using PyInstaller in \"onefile\" mode is launched by a privileged user (at least more than the current one) which have his \"TempPath\" resolving to a world writable directory. This is the case for example if the software is launched as a service or as a scheduled task using a system account (TempPath will be C:\\Windows\\Temp). In order to be exploitable the software has to be (re)started after the attacker launch the exploit program, so for a service launched at startup, a service restart is needed (e.g. after a crash or an upgrade)."
            }
        ],
        "metrics": [
            {
                "cvss-v_3_1": {
                    "attackComplexity": "HIGH",
                    "attackVector": "LOCAL",
                    "availabilityImpact": "HIGH",
                    "baseScore": 7,
                    "baseSeverity": "HIGH",
                    "confidentialityImpact": "HIGH",
                    "integrityImpact": "HIGH",
                    "privilegesRequired": "LOW",
                    "scope": "UNCHANGED",
                    "userInteraction": "NONE",
                    "vectorString": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H",
                    "version": "3.1"
                }
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "CWE-ID": "CWE-250 Execution with Unnecessary Privileges",
                        "description": "CWE-250 Execution with Unnecessary Privileges",
                        "lang": "eng",
                        "type": "CWE"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://github.com/pyinstaller/pyinstaller/security/advisories/GHSA-7fcj-pq9j-wh2r",
                "refsource": "CONFIRM",
                "url": "https://github.com/pyinstaller/pyinstaller/security/advisories/GHSA-7fcj-pq9j-wh2r"
            }
        ],
        "source": {
            "advisory": "GHSA-7fcj-pq9j-wh2r",
            "discovery": "UNKNOWN"
        }
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}