{
    "CVE_data_meta": {
        "ASSIGNER": "talos-cna@cisco.com",
        "ID": "CVE-2019-5010",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "Python.org CPython 2.7.11 Python.org CPython 3.6.6 Python.org CPython 3.5.2 Python.org CPython 3 master at 480833808e918a1dcebbbcfd07d5a8de3c5c2a66"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "n/a"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability."
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "denial of service",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0758",
                "refsource": "MISC",
                "url": "https://talosintelligence.com/vulnerability_reports/TALOS-2019-0758"
            },
            {
                "name": "RHSA-2019:3520",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2019:3520"
            },
            {
                "name": "RHSA-2019:3725",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2019:3725"
            },
            {
                "name": "openSUSE-SU-2020:0086",
                "refsource": "SUSE",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
            },
            {
                "name": "GLSA-202003-26",
                "refsource": "GENTOO",
                "url": "https://security.gentoo.org/glsa/202003-26"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}