{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2019-14864",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "Ansible versions 2.9.x before 2.9.1"
                                },
                                {
                                    "version_value": "Ansible versions 2.8.x before 2.8.7"
                                },
                                {
                                    "version_value": "Ansible versions 2.7.x before 2.7.15"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "Red Hat"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "Ansible, versions 2.9.x before 2.9.1, 2.8.x before 2.8.7 and Ansible versions 2.7.x before 2.7.15, is not respecting the flag no_log set it to True when Sumologic and Splunk callback plugins are used send tasks results events to collectors. This would discloses and collects any sensitive data."
            }
        ],
        "metrics": [
            {
                "cvss-v_3_0": {
                    "vectorString": "5.7/CVSS:3.0/AV:N/AC:L/PR:L/UI:R/S:U/C:H/I:N/A:N",
                    "version": "3.0"
                }
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "CWE-ID": "CWE-117",
                        "description": "CWE-117",
                        "lang": "eng",
                        "type": "CWE"
                    }
                ],
                [
                    {
                        "CWE-ID": "CWE-532",
                        "description": "CWE-532",
                        "lang": "eng",
                        "type": "CWE"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14864",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14864"
            },
            {
                "name": "https://github.com/ansible/ansible/issues/63522",
                "refsource": "MISC",
                "url": "https://github.com/ansible/ansible/issues/63522"
            },
            {
                "name": "https://github.com/ansible/ansible/pull/63527",
                "refsource": "MISC",
                "url": "https://github.com/ansible/ansible/pull/63527"
            },
            {
                "name": "openSUSE-SU-2020:0513",
                "refsource": "SUSE",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html"
            },
            {
                "name": "openSUSE-SU-2020:0523",
                "refsource": "SUSE",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}