{
    "CVE_data_meta": {
        "ASSIGNER": "psirt@us.ibm.com",
        "DATE_PUBLIC": "2020-02-18T00:00:00",
        "ID": "CVE-2020-4161",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "11.5"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "IBM"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "IBM DB2 for Linux, UNIX and Windows (includes DB2 Connect Server) 11.5 could allow an authenticated attacker to cause a denial of service due to incorrect handling of certain commands. IBM X-Force ID: 174341."
            }
        ],
        "metrics": [
            {
                "cvss-v_3_0": {
                    "BM": {
                        "A": "H",
                        "AC": "L",
                        "AV": "N",
                        "C": "N",
                        "I": "N",
                        "PR": "L",
                        "S": "U",
                        "SCORE": "6.500",
                        "UI": "N"
                    },
                    "TM": {
                        "E": "U",
                        "RC": "C",
                        "RL": "O"
                    }
                }
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "description": "Denial of Service",
                        "lang": "eng",
                        "type": "text"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "https://www.ibm.com/support/pages/node/2874621",
                "refsource": "CONFIRM",
                "url": "https://www.ibm.com/support/pages/node/2874621"
            },
            {
                "name": "ibm-db2-cve20204161-dos (174341)",
                "refsource": "XF",
                "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/174341"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}