{
    "CVE_data_meta": {
        "ASSIGNER": "secalert@redhat.com",
        "ID": "CVE-2018-14647",
        "STATE": "PUBLIC",
        "UPDATED": "2020-06-15"
    },
    "cna-container": {
        "affected": {
            "vendors": [
                {
                    "products": [
                        {
                            "versions": [
                                {
                                    "version_value": "3.8, 3.7, 3.6, 3.5, 3.4, 2.7"
                                }
                            ]
                        }
                    ],
                    "vendor_name": "The Python Project"
                }
            ]
        },
        "descriptions": [
            {
                "lang": "eng",
                "value": "Python's elementtree C accelerator failed to initialise Expat's hash salt during initialization. This could make it easy to conduct denial of service attacks against Expat by constructing an XML document that would cause pathological hash collisions in Expat's internal data structures, consuming large amounts CPU and RAM. Python 3.8, 3.7, 3.6, 3.5, 3.4, 2.7 are believed to be vulnerable."
            }
        ],
        "metrics": [
            {
                "cvss-v_3_0": {
                    "vectorString": "5.3/CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
                    "version": "3.0"
                }
            }
        ],
        "problemtypes": {
            "descriptions": [
                [
                    {
                        "CWE-ID": "CWE-665",
                        "description": "CWE-665",
                        "lang": "eng",
                        "type": "CWE"
                    }
                ],
                [
                    {
                        "CWE-ID": "CWE-335",
                        "description": "CWE-335",
                        "lang": "eng",
                        "type": "CWE"
                    }
                ]
            ]
        },
        "references": [
            {
                "name": "DSA-4306",
                "refsource": "DEBIAN",
                "url": "https://www.debian.org/security/2018/dsa-4306"
            },
            {
                "name": "USN-3817-2",
                "refsource": "UBUNTU",
                "url": "https://usn.ubuntu.com/3817-2/"
            },
            {
                "name": "1041740",
                "refsource": "SECTRACK",
                "url": "http://www.securitytracker.com/id/1041740"
            },
            {
                "name": "105396",
                "refsource": "BID",
                "url": "http://www.securityfocus.com/bid/105396"
            },
            {
                "name": "DSA-4307",
                "refsource": "DEBIAN",
                "url": "https://www.debian.org/security/2018/dsa-4307"
            },
            {
                "name": "https://bugs.python.org/issue34623",
                "refsource": "MISC",
                "url": "https://bugs.python.org/issue34623"
            },
            {
                "name": "USN-3817-1",
                "refsource": "UBUNTU",
                "url": "https://usn.ubuntu.com/3817-1/"
            },
            {
                "name": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647",
                "refsource": "CONFIRM",
                "url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-14647"
            },
            {
                "name": "FEDORA-2019-0c91ce7b3c",
                "refsource": "FEDORA",
                "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/RBJCB2HWOJLP3L7CUQHJHNBHLSVOXJE5/"
            },
            {
                "name": "RHSA-2019:1260",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2019:1260"
            },
            {
                "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1834-1] python2.7 security update",
                "refsource": "MLIST",
                "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00022.html"
            },
            {
                "name": "[debian-lts-announce] 20190625 [SECURITY] [DLA 1835-1] python3.4 security update",
                "refsource": "MLIST",
                "url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00023.html"
            },
            {
                "name": "RHSA-2019:2030",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2019:2030"
            },
            {
                "name": "RHSA-2019:3725",
                "refsource": "REDHAT",
                "url": "https://access.redhat.com/errata/RHSA-2019:3725"
            },
            {
                "name": "openSUSE-SU-2020:0086",
                "refsource": "SUSE",
                "url": "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html"
            }
        ]
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "5.0"
}